Create table LMS_MEMBERS
(
	MEMBER_ID Varchar2(10),
	MEMBER_NAME Varchar2(30) NOT NULL,
	CITY VARCHAR2(20),
	DATE_REGISTER Date NOT NULL,
	DATE_EXPIRE Date ,
	MEMBERSHIP_STATUS Varchar2(15)NOT NULL,
	Constraints LMS_cts1 PRIMARY KEY(MEMBER_ID)
);

Create table LMS_SUPPLIERS_DETAILS
(
	SUPPLIER_ID Varchar2(3),
	SUPPLIER_NAME Varchar2(30) NOT NULL,
	ADDRESS	Varchar2(50),
	CONTACT Number(10) NOT NULL,
	EMAIL Varchar2(15) NOT NULL,
	Constraints LMS_cts2 PRIMARY KEY(SUPPLIER_ID)
);

Create table LMS_FINE_DETAILS
(
	FINE_RANGE Varchar2(3),
	FINE_AMOUNT Number(10,2) NOT NULL,
	Constraints LMS_cts3 PRIMARY KEY(FINE_RANGE)
);


Create table LMS_BOOK_DETAILS
(
	BOOK_CODE Varchar2(10),	
	BOOK_TITLE Varchar2(50) NOT NULL,
	CATEGORY Varchar2(15) NOT NULL,
	AUTHOR Varchar2(30) NOT NULL,
	PUBLICATION Varchar2(30),
	PUBLISH_DATE Date,
	BOOK_EDITION Number(2),
	PRICE Number(8,2) NOT NULL,	
	RACK_NUM Varchar2(3),
	DATE_ARRIVAL Date NOT NULL, 		
	SUPPLIER_ID Varchar2(3) NOT NULL,
	Constraints LMS_cts4 PRIMARY KEY(BOOK_CODE), 
        Constraints LMS_cts41 FOREIGN KEY(SUPPLIER_ID) References LMS_SUPPLIERS_DETAILS(SUPPLIER_ID)
);


Create table LMS_BOOK_ISSUE
(
	BOOK_ISSUE_NO Number,
	MEMBER_ID Varchar2(10) NOT NULL,
	BOOK_CODE Varchar2(10) NOT NULL,
	DATE_ISSUE Date NOT NULL,
	DATE_RETURN Date NOT NULL,
        DATE_RETURNED Date NULL,
	BOOK_ISSUE_STATUS Varchar2(20) NOT NULL,
	FINE_RANGE vARCHAR2(3),
	Constraints LMS_cts5 PRIMARY KEY(BOOK_ISSUE_NO),
        Constraints LMS_Mem FOREIGN KEY(MEMBER_ID) References LMS_MEMBERS(MEMBER_ID),
        Constraints LMS_BookDetail FOREIGN KEY(BOOK_CODE) References LMS_BOOK_DETAILS(BOOK_CODE),
	Constraints LMS_FineDetail FOREIGN KEY(FINE_RANGE) References LMS_FINE_DETAILS(FINE_RANGE)
);
